---
tags:
  - flashcards/js
---
### Q : `.throw()`로 오류 잡기
- 출력 결과
```js
function* gen() {
  try {
    yield "Trying...";
    yield "Trying harder...";
    yield "Trying even harder..";
  }
  catch(err) {
    console.log("Error: " + err);
  }
}
const myGenerator = gen();
myGenerator.next();
// {value: "Trying...", done: false}
myGenerator.next();
// {value: "Trying harder...", done: false}
myGenerator.throw("ooops");
```
?
```js
// Error: ooops
```
- `.throw()` 호출 이후에는 제너레이터 종료됨